# Generated by Django 4.1.5 on 2023-01-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_blog', '0002_remove_usuario_fecha_nacimieento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
