# Generated by Django 4.1.5 on 2023-01-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagina_blog', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('fecha_publicacion', models.DateField(null=True)),
                ('autor', models.CharField(max_length=64)),
            ],
        ),
    ]
