# Generated by Django 4.1.5 on 2023-01-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_blog', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='cuerpo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
