# Generated by Django 4.1.5 on 2023-01-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_blog', '0005_noticias_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
