# Generated by Django 4.1.5 on 2023-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_blog', '0006_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
    ]
